
image:
#  - Visual Studio 2017
  - Ubuntu2004
  - macos

matrix:
  fast_finish: true

for:
  - matrix:
        only:
          - image: Visual Studio 2017
    environment:
        JAMOVI_URL: https://www.jamovi.org/downloads/jamovi-2.3.24.0-win64.zip
        JAMOVI_HOME: jamovi-2.3.24.0-win64
        R_VERSION: 4.1.2
        PYTHON: "C:\\Python38-x64\\python"
        GITHUB_PAT:
          secure: ACjmkFTJuQP7T/3iT+RbRrGXpbuhHKOCV59xP9Rth+mTr8PSpNxdceBEoPWDjdp9
    before_build:
      - tzutil /s "GMT Standard Time"
    install:
      - "%PYTHON% -m pip install -r requirements.txt"
    #   - curl -o jamovi.zip %JAMOVI_URL%
    #   - ps: Expand-Archive -Path jamovi.zip -DestinationPath .
    #   - curl -o Rtools.exe https://cran.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe
    #   - Rtools.exe /VERYSILENT -NoNewWindow -Wait
    #   - git submodule update --init --recursive
    #   - cd jamovi-compiler
    #   - npm install
    #   - cd %APPVEYOR_BUILD_FOLDER%
    build_script:
      - "echo moo"
      #- "%PYTHON% generate.py"

  - matrix:
        only:
          - image: macos
    environment:
        JAMOVI_URL: https://www.jamovi.org/downloads/jamovi-2.4.0.0-macos.zip
        JAMOVI_HOME: jamovi.app
        R_VERSION: 4.1.3
        PYTHON: "python3"
        APPVEYOR_CONSOLE_DISABLE_PTY: true
        GITHUB_PAT:
          secure: ACjmkFTJuQP7T/3iT+RbRrGXpbuhHKOCV59xP9Rth+mTr8PSpNxdceBEoPWDjdp9
    install:
      - $PYTHON -m pip install --user -r requirements.txt
      - curl -o jamovi.zip $JAMOVI_URL
      - unzip jamovi.zip
      - git submodule update --init --recursive
      - cd jamovi-compiler
      - npm install
      - cd $APPVEYOR_BUILD_FOLDER
    build_script:
      - $PYTHON generate.py

  - matrix:
        only:
          - image: Ubuntu2004
    environment:
        JAMOVI_HOME: flatpak
        R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
        APPVEYOR_CONSOLE_DISABLE_PTY: true
        CRAN_MIRROR: https://repo.jamovi.org/cran/2023-04-07,https://packagemanager.rstudio.com/cran/2023-04-07
        GITHUB_PAT:
          secure: ACjmkFTJuQP7T/3iT+RbRrGXpbuhHKOCV59xP9Rth+mTr8PSpNxdceBEoPWDjdp9
    install:
      - sudo apt update
      - sudo apt install -y flatpak python3 python3-pip gnutls-bin
      - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - bash install-flatpak.sh
      - export R_VERSION=`flatpak run org.jamovi.jamovi --r-version`
      - export APPVEYOR_SAVE_CACHE_ON_ERROR=true
      - python3 -m pip install -r requirements.txt
      - git submodule update --init --recursive
      - cd jamovi-compiler
      - npm install
      - cd $APPVEYOR_BUILD_FOLDER
    build_script:
      - python3 generate.py
    #cache:
    #  - /home/appveyor/.local/share/flatpak/app/org.jamovi.jamovi -> install-flatpak.sh


deploy:
  provider: FTP
  protocol: sftp
  host: jamovi.org
  username:
    secure: VRak1kh1UY0ykCgn74VqqA==
  password:
    secure: AVAH21aBWxVg/1Lyd9w88Q==
  folder: library.jamovi.org

# deploy:
#     provider: S3
#     access_key_id:
#         secure: N8joJYrY0qe2TVtDes16QkENBiJxNI5mGyQJVPNvwBI=
#     secret_access_key:
#         secure: nY0Q0+LKzvSchTdNB2rrLvqWQYCubOnWO5OpZ1tLgLWGRQad5HWDK2jJ7Q4WDnV3
#     bucket: jamovi-library
#     region: us-east-1
#     set_public: true
#     on:
#         branch: master
