
image:
  - Ubuntu
  - macos
  - Visual Studio 2017

matrix:
  fast_finish: true

environment:
    CRAN_MIRROR: https://cran.microsoft.com/snapshot/2020-08-24

for:
  - matrix:
        only:
          - image: Visual Studio 2017
    environment:
        JAMOVI_URL: https://www.jamovi.org/downloads/jamovi-1.2.19.0-win64.zip
        JAMOVI_HOME: jamovi-1.2.19.0-win64
        R_VERSION: 3.6.3
        PYTHON: "C:\\Python38-x64\\python"
    before_build:
      - tzutil /s "GMT Standard Time"
    install:
      - "%PYTHON% -m pip install -r requirements.txt"
      - curl -o jamovi.zip %JAMOVI_URL%
      - ps: Expand-Archive -Path jamovi.zip -DestinationPath .
      - curl -o Rtools.exe https://cran.r-project.org/bin/windows/Rtools/Rtools35.exe
      - Rtools.exe /VERYSILENT -NoNewWindow -Wait
      - git submodule update --init --recursive
      - cd jamovi-compiler
      - npm install
      - cd %APPVEYOR_BUILD_FOLDER%
    build_script:
      - "%PYTHON% generate.py"

  - matrix:
        only:
          - image: macos
    environment:
        JAMOVI_URL: https://www.jamovi.org/downloads/jamovi-dev.zip
        JAMOVI_HOME: jamovi.app
        R_VERSION: 4.0.2
        PYTHON: "python3"
        APPVEYOR_CONSOLE_DISABLE_PTY: true
    install:
      - $PYTHON -m pip install --user -r requirements.txt
      - curl -o jamovi.zip $JAMOVI_URL
      - unzip jamovi.zip
      - git submodule update --init --recursive
      - cd jamovi-compiler
      - npm install
      - cd $APPVEYOR_BUILD_FOLDER
    build_script:
      - $PYTHON generate.py

  - matrix:
        only:
          - image: Ubuntu
    environment:
        JAMOVI_HOME: flatpak
        R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
        APPVEYOR_CONSOLE_DISABLE_PTY: true
        CRAN_MIRROR: https://www.jamovi.org/downloads/repo/4.0.2/2020-08-24,https://cran.microsoft.com/snapshot/2020-08-24
    install:
      - sudo add-apt-repository ppa:alexlarsson/flatpak
      - sudo apt update
      - sudo apt install -y flatpak python3.7 python3-pip
      - bash install-flatpak.sh
      - export R_VERSION=`flatpak run org.jamovi.jamovi --r-version`
      - export APPVEYOR_SAVE_CACHE_ON_ERROR=true
      - python3.7 -m pip install -r requirements.txt
      - git submodule update --init --recursive
      - cd jamovi-compiler
      - npm install
      - cd $APPVEYOR_BUILD_FOLDER
    build_script:
      - python3.7 generate.py
    cache:
      - /home/appveyor/.local/share/flatpak/app/org.jamovi.jamovi -> install-flatpak.sh


deploy:
  provider: FTP
  protocol: sftp
  host: jamovi.org
  username:
    secure: VRak1kh1UY0ykCgn74VqqA==
  password:
    secure: 46x3rwu0Ts7zdn11ohXX/w==
  folder: library.jamovi.org

# deploy:
#     provider: S3
#     access_key_id:
#         secure: N8joJYrY0qe2TVtDes16QkENBiJxNI5mGyQJVPNvwBI=
#     secret_access_key:
#         secure: nY0Q0+LKzvSchTdNB2rrLvqWQYCubOnWO5OpZ1tLgLWGRQad5HWDK2jJ7Q4WDnV3
#     bucket: jamovi-library
#     region: us-east-1
#     set_public: true
#     on:
#         branch: master
