image:
  - macos
  - Visual Studio 2017

for:
  - matrix:
        only:
          - image: Visual Studio 2017
    environment:
        JAMOVI_URL: https://www.jamovi.org/downloads/jamovi-1.1.9.0-R3.6-win64.zip
        JAMOVI_HOME: jamovi-1.1.9.0-R3.6-win64
        PYTHON: "C:\\Python38-x64\\python"
    before_build:
      - tzutil /s "GMT Standard Time"
    install:
      - "%PYTHON% -m pip install -r requirements.txt"
      - curl -o jamovi.zip %JAMOVI_URL%
      - ps: Expand-Archive -Path jamovi.zip -DestinationPath .
      - git submodule update --init --recursive
      - cd jamovi-compiler
      - npm install
      - cd %APPVEYOR_BUILD_FOLDER%
    build_script:
      - "%PYTHON% generate.py"

  - matrix:
        only:
          - image: macos
    environment:
        JAMOVI_URL: https://www.jamovi.org/downloads/jamovi-1.2.1.0-macos.zip
        JAMOVI_HOME: jamovi.app
        PYTHON: "python3"
    install:
      - $PYTHON -m pip install -r requirements.txt
      - curl -o jamovi.zip $JAMOVI_URL
      - unzip jamovi.zip
      - git submodule update --init --recursive
      - cd jamovi-compiler
      - npm install
      - cd $APPVEYOR_BUILD_FOLDER
    build_script:
      - $PYTHON generate.py

artifacts:
  - path: '*.log'
    name: Build Logs

deploy:
    provider: S3
    access_key_id:
        secure: N8joJYrY0qe2TVtDes16QkENBiJxNI5mGyQJVPNvwBI=
    secret_access_key:
        secure: nY0Q0+LKzvSchTdNB2rrLvqWQYCubOnWO5OpZ1tLgLWGRQad5HWDK2jJ7Q4WDnV3
    bucket: jamovi-library
    region: us-east-1
    set_public: true
